settings:
  mace-crafted: false  # Changes to true when the Mace is crafted
  mace-owner: null  # Stores the UUID of the current owner, or null if no owner
  announce-mace-messages: true  # If true, broadcasts when the Mace is crafted or lost

# Stores whether an offline player logged out with the Mace.
# If set to true, the Mace is in their inventory or Ender Chest when they logged out.
# Used to prevent crafting if the Mace still exists in an offline player’s possession.
# This is automatically updated when a player logs out or the server shuts down.
offline_inventory: {}

# Customizable messages
messages:
  crafted: "&b[OneMace] &eThe Mace has been crafted!"
  lost: "&b[OneMace] &eThe Mace has been lost!"
