name: onemace
version: '${version}'
main: net.mattwhyy.onemace.OneMace
api-version: '26.2'
commands:
  onemace:
    description: Main command for OneMace
    usage: /onemace <subcommand>
permissions:
  onemace.admin:
    description: Allows using OneMace admin subcommands
    default: op
